version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sml1234
  python:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
  grafana:
    depends_on: mongo
    image: grafana/grafana
    ports:
      - 3000:3000
