version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    env_file:
      - .env
    entrypoint: [ "./entrypoint.sh" ]
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb


  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    env_file:
      - .env
    links:
      - influxdb
    ports:
      - '8125:8125/udp'

  python:
    build: ./pythonworker
    container_name: pythonworker
    restart: always
    volumes:
      - pythonworker_storage:/var/lib/pythonworker:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    links:
      - influxdb


  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
  pythonworker_storage: {}
